"""Create Big Screen's zipimport yt-dlp runtime from upstream source trees.

The regular Quest build uses yt-dlp's signed-release asset after checking its
SHA-256 because that keeps normal builds fast. This helper is the reproducible
source path: it packages the yt-dlp Python tree plus the locally rebuilt EJS
solver payload without relying on Make, zip, or other Unix-only utilities.
"""

from __future__ import annotations

import argparse
import io
import pathlib
import zipfile


ARCHIVE_TIMESTAMP = (2000, 1, 1, 1, 1, 0)
EJS_PACKAGE_FILES = (
    "__init__.py",
    "yt/__init__.py",
    "yt/solver/__init__.py",
)


def version_source(version: str) -> bytes:
    """Reproduce the small metadata module generated by setuptools-scm."""

    version_tuple = tuple(int(part) for part in version.split("."))
    return f'''# file generated by setuptools-scm
# don't change, don't track in version control

__all__ = [
    "__version__",
    "__version_tuple__",
    "version",
    "version_tuple",
    "__commit_id__",
    "commit_id",
]

TYPE_CHECKING = False
if TYPE_CHECKING:
    from typing import Tuple
    from typing import Union

    VERSION_TUPLE = Tuple[Union[int, str], ...]
    COMMIT_ID = Union[str, None]
else:
    VERSION_TUPLE = object
    COMMIT_ID = object

version: str
__version__: str
__version_tuple__: VERSION_TUPLE
version_tuple: VERSION_TUPLE
commit_id: COMMIT_ID
__commit_id__: COMMIT_ID

__version__ = version = {version!r}
__version_tuple__ = version_tuple = {version_tuple!r}

__commit_id__ = commit_id = None
'''.encode()


def collect_payload(
    yt_dlp_source: pathlib.Path,
    ejs_source: pathlib.Path,
    ejs_version: str,
) -> dict[str, bytes]:
    """Collect only the files used by upstream's zipimport build target."""

    payload: dict[str, bytes] = {}
    yt_package = yt_dlp_source / "yt_dlp"
    if not (yt_package / "version.py").is_file():
        raise FileNotFoundError(f"Invalid yt-dlp source tree: {yt_dlp_source}")

    for source in sorted(yt_package.rglob("*")):
        if not source.is_file() or source.suffix not in {".py", ".js"}:
            continue
        relative = source.relative_to(yt_dlp_source).as_posix()
        # These hook files help PyInstaller analyze desktop executables. They
        # are intentionally absent from yt-dlp's portable zipimport release.
        if relative.startswith("yt_dlp/__pyinstaller/"):
            continue
        if relative == "yt_dlp/__main__.py":
            # A zipapp starts through a root-level __main__.py. Upstream's
            # Makefile deliberately excludes the package-local copy too.
            continue
        payload[relative] = source.read_bytes()
    payload["__main__.py"] = (yt_package / "__main__.py").read_bytes()

    ejs_package = ejs_source / "yt_dlp_ejs"
    for relative in EJS_PACKAGE_FILES:
        source = ejs_package / relative
        if not source.is_file():
            raise FileNotFoundError(f"Missing EJS package source: {source}")
        payload[f"yt_dlp_ejs/{relative}"] = source.read_bytes()
    payload["yt_dlp_ejs/_version.py"] = version_source(ejs_version)

    for built_name, package_name in (
        ("yt.solver.core.min.js", "core.min.js"),
        ("yt.solver.lib.min.js", "lib.min.js"),
    ):
        source = ejs_source / "dist" / built_name
        if not source.is_file():
            raise FileNotFoundError(
                f"Missing rebuilt EJS solver {source}; run hatch_build.py first"
            )
        payload[f"yt_dlp_ejs/yt/solver/{package_name}"] = source.read_bytes()

    return payload


def write_zipimport(output: pathlib.Path, payload: dict[str, bytes]) -> None:
    """Write deterministic ZIP entries and prepend yt-dlp's normal shebang."""

    zip_buffer = io.BytesIO()
    with zipfile.ZipFile(
        zip_buffer,
        mode="w",
        compression=zipfile.ZIP_DEFLATED,
        compresslevel=9,
    ) as archive:
        for name in sorted(payload):
            info = zipfile.ZipInfo(name, ARCHIVE_TIMESTAMP)
            info.compress_type = zipfile.ZIP_DEFLATED
            info.external_attr = 0o644 << 16
            archive.writestr(info, payload[name], compresslevel=9)

    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_bytes(b"#!/usr/bin/env python3\n" + zip_buffer.getvalue())


def compare_reference(reference: pathlib.Path, payload: dict[str, bytes]) -> None:
    """Require the source-built payload to equal the pinned official release."""

    with zipfile.ZipFile(reference) as archive:
        reference_names = set(archive.namelist())
        built_names = set(payload)
        if reference_names != built_names:
            missing = sorted(reference_names - built_names)
            extra = sorted(built_names - reference_names)
            raise RuntimeError(
                "Source/release entry mismatch. "
                f"Missing from source build: {missing[:10]}; extra: {extra[:10]}"
            )
        changed = [
            name for name in sorted(payload) if archive.read(name) != payload[name]
        ]
        if changed:
            raise RuntimeError(
                "Source-built files differ from the pinned official release: "
                + ", ".join(changed[:10])
            )


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--yt-dlp-source", required=True, type=pathlib.Path)
    parser.add_argument("--ejs-source", required=True, type=pathlib.Path)
    parser.add_argument("--ejs-version", required=True)
    parser.add_argument("--output", required=True, type=pathlib.Path)
    parser.add_argument("--reference", type=pathlib.Path)
    args = parser.parse_args()

    payload = collect_payload(args.yt_dlp_source, args.ejs_source, args.ejs_version)
    if args.reference:
        compare_reference(args.reference, payload)
    write_zipimport(args.output, payload)
    print(f"Built {args.output} from {len(payload)} verified source files.")


if __name__ == "__main__":
    main()
